In [1]:
import cv2
import matplotlib.pyplot as plt
import imageio
from skimage.transform import resize
from skimage import color
import numpy as np

In [2]:
# esto va a ir en la ia de verdad, solo no en la prueba que ando haciendo
import numpy as np
import matplotlib.pyplot as plt
import os 
from skimage.transform import resize
categorias = []
labelsNS = []
labels = []
imagenes = []
categorias = os.listdir("Ropa 28 x 28")

In [3]:
x=0
for directorio in categorias:
    for imagen in os.listdir("Ropa 28 x 28\\"+directorio):
        img = imageio.imread("Ropa 28 x 28\\"+directorio+"\\"+imagen)
        imagenes.append(img)
        labels.append(x)
        labelsNS.append(x)
    x += 1

In [4]:
print(type(imagenes))
print(type(imagenes[0]))
print(imagenes[0].shape)
print(imagenes[0][0].shape)
print(type(imagenes[0][0]))

<class 'list'>
<class 'imageio.core.util.Array'>
(28, 28, 3)
(28, 3)
<class 'imageio.core.util.Array'>


In [5]:
imagenes

[Array([[[174, 166, 205],
         [176, 168, 205],
         [177, 169, 206],
         ...,
         [220, 221, 251],
         [216, 221, 253],
         [207, 215, 251]],
 
        [[176, 168, 205],
         [181, 173, 210],
         [180, 172, 209],
         ...,
         [218, 219, 249],
         [213, 218, 250],
         [215, 223, 255]],
 
        [[179, 171, 208],
         [179, 171, 208],
         [175, 169, 205],
         ...,
         [220, 221, 251],
         [217, 220, 251],
         [219, 225, 255]],
 
        ...,
 
        [[167, 159, 198],
         [175, 167, 206],
         [165, 157, 196],
         ...,
         [200, 202, 241],
         [201, 203, 242],
         [203, 202, 242]],
 
        [[167, 159, 200],
         [170, 162, 203],
         [171, 163, 204],
         ...,
         [200, 202, 241],
         [198, 200, 239],
         [201, 203, 244]],
 
        [[175, 167, 208],
         [174, 166, 207],
         [170, 163, 204],
         ...,
         [197, 199, 238],
  

In [6]:
lista = imagenes
imagenes = np.asarray(imagenes)

In [7]:
print(type(imagenes))
print(type(imagenes[0]))
print(imagenes[0].shape)
print(imagenes[0][0].shape)
print(type(imagenes[0][0]))
print(imagenes)
print(imagenes.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(28, 28, 3)
(28, 3)
<class 'numpy.ndarray'>
[[[[174 166 205]
   [176 168 205]
   [177 169 206]
   ...
   [220 221 251]
   [216 221 253]
   [207 215 251]]

  [[176 168 205]
   [181 173 210]
   [180 172 209]
   ...
   [218 219 249]
   [213 218 250]
   [215 223 255]]

  [[179 171 208]
   [179 171 208]
   [175 169 205]
   ...
   [220 221 251]
   [217 220 251]
   [219 225 255]]

  ...

  [[167 159 198]
   [175 167 206]
   [165 157 196]
   ...
   [200 202 241]
   [201 203 242]
   [203 202 242]]

  [[167 159 200]
   [170 162 203]
   [171 163 204]
   ...
   [200 202 241]
   [198 200 239]
   [201 203 244]]

  [[175 167 208]
   [174 166 207]
   [170 163 204]
   ...
   [197 199 238]
   [196 198 239]
   [197 199 240]]]


 [[[176 171 211]
   [177 172 212]
   [177 172 212]
   ...
   [223 219 252]
   [207 205 242]
   [207 209 250]]

  [[175 168 209]
   [179 174 214]
   [177 172 212]
   ...
   [221 217 250]
   [222 222 255]
   [209 213 251]]

  [[180 174

In [8]:
#for x in range(len(labels)):
#    if labels[x] == 0:
#        labels[x] = "Camisa" 
#    elif labels[x] == 1:
#        labels[x] = "Pantalón" 
#    elif labels[x] == 2:
#        labels[x] = "Pantaloneta" 
#    elif labels[x] == 3:
#        labels[x] = "Playera"
#    else:
#        labels[x] = "Zapato"

In [9]:
print(labels)
print(imagenes[0].shape)
print(imagenes[10].shape)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
(28, 28, 3)
(28, 28, 3)


In [10]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers import Flatten
from keras.layers import Conv2D
from keras.layers import Dropout
from keras.layers import MaxPooling2D

In [11]:
model = Sequential([
    Conv2D(32,(3,3),input_shape=(28,28,3),activation="relu"),
    MaxPooling2D(2,2),
    Conv2D(32,(3,3),activation="relu"),
    MaxPooling2D(2,2),
    Dropout(0.5),
    
    Flatten(),
    Dense(64,activation="relu"),
    Dense(32,activation="relu"),
    Dense(128,activation="relu"),
    Dense(10,activation="softmax"),
])

In [12]:
model.compile(optimizer="adam",
             loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 32)         0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 5, 5, 32)          0         
                                                                 
 flatten (Flatten)           (None, 800)               0

In [13]:
labelsNS = np.array(labelsNS)
model.fit(imagenes,labelsNS, epochs=30)

Epoch 1/30
5/5 [==============================] - 1s 38ms/step - loss: 13.4022 - accuracy: 0.1628
Epoch 2/30
5/5 [==============================] - 0s 8ms/step - loss: 4.7297 - accuracy: 0.2636
Epoch 3/30
5/5 [==============================] - 0s 8ms/step - loss: 3.0838 - accuracy: 0.2713
Epoch 4/30
5/5 [==============================] - 0s 10ms/step - loss: 2.3844 - accuracy: 0.3411
Epoch 5/30
5/5 [==============================] - 0s 8ms/step - loss: 1.9739 - accuracy: 0.3101
Epoch 6/30
5/5 [==============================] - 0s 9ms/step - loss: 1.5512 - accuracy: 0.4186
Epoch 7/30
5/5 [==============================] - 0s 7ms/step - loss: 1.4094 - accuracy: 0.4109
Epoch 8/30
5/5 [==============================] - 0s 10ms/step - loss: 1.5099 - accuracy: 0.4419
Epoch 9/30
5/5 [==============================] - 0s 10ms/step - loss: 1.3626 - accuracy: 0.5271
Epoch 10/30
5/5 [==============================] - 0s 10ms/step - loss: 1.1001 - accuracy: 0.6124
Epoch 11/30
5/5 [================

In [14]:
test_loss, test_acc = model.evaluate(imagenes,labelsNS)
print("Test Accuracy: ",test_acc)
print("Test Loss: ",test_loss)

5/5 [==============================] - 0s 5ms/step - loss: 0.1054 - accuracy: 0.9690
Test Accuracy:  0.9689922332763672
Test Loss:  0.10535186529159546


In [15]:
prediction= model.predict(imagenes)

In [16]:
imagenes2=[]
labels2=[]
x=0
for directorio in categorias:
    for imagen in os.listdir("prueba\\"+directorio):
        img = imageio.imread("prueba\\"+directorio+"\\"+imagen)
        imgx = resize(img,(28,28,3))
        imagenes2.append(imgx)
        labels2.append(x)
    x += 1

In [17]:
imagenes2 = np.asarray(imagenes2)
prediction2= model.predict(imagenes2)

In [18]:
print(np.argmax(prediction2[0]))
print(labels2[0])

0
0


In [23]:
#esto es para el frontend
from tkinter import *
from tkinter import ttk
from tkinter import filedialog, Label,PhotoImage, Button

def porcentajes(i,predictions_array,true_label,img):
    predictions_array,true_label,img = predictions_array[i],true_label[i],img[i]
    predicted_label = np.argmax(predictions_array)
    print(np.argmax(predictions_array))
    texto = categorias[predicted_label], " ",100*np.max(predictions_array), " ", categorias[true_label]
    print(texto)
    lblPorcentaje = Label(raiz,text=texto,bg="#077AAE",fg="#FEFEFE").pack()
porcentajes(13,prediction2,labels2,imagenes2)

0
('Camisa', ' ', 11.634163558483124, ' ', 'Zapato')


In [21]:
#esto es para el frontend
from tkinter import *
from tkinter import ttk
from tkinter import filedialog, Label,PhotoImage, Button
from PIL import Image
#from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
raiz = Tk()
raiz.geometry("450x350")
raiz.title("Clasificador")
frame= Frame(raiz, bg="blue")
entero_prueba = ttk.Entry(raiz,width=20)
entero_prueba.pack()
lblPorcentaje = Label(raiz,text="",bg="#077AAE",fg="#FEFEFE").pack()
i=0

# aquí vamos a ver que tan probable es que salga esta imagen
def testeo_si_testeo():
    i= int(entero_prueba.get())
    porcentajes(i,prediction2,labels2,imagenes2)

In [22]:
boton_prueba= Button(raiz, text="Ver", command=testeo_si_testeo)
boton_prueba.pack()
img2 = Image.fromarray(imagenes2[i])
img2.save('C:\\Users\\HP15DA0023LA\\Untitled Folder\\my.png')
ix = PhotoImage(file="C:\\Users\\HP15DA0023LA\\Untitled Folder\\my.png")
lbl_img = Label(raiz, image = ix)
lbl_img.pack()

TypeError: Cannot handle this data type: (1, 1, 3), <f8

In [ ]:
raiz.mainloop()