In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
import numpy as np
import matplotlib.pyplot as plt
#esto es para el frontend
from tkinter import *
from tkinter import ttk
from tkinter import filedialog, Label,PhotoImage, Button

In [3]:
fashion_mnist = keras.datasets.fashion_mnist
pru= keras.datasets.fashion_mnist

In [4]:
(train_images, train_labels),(test_images, test_labels) = fashion_mnist.load_data()

In [5]:
categorias = ["Playera","Pantalon","Sueter","Vestido","Abrigo","Sandalia",
              "Camisa","Sneaker","bolsa","Botín"]

In [6]:
print("Train_Images shape: ",train_images.shape)
print("Train_Labels shape:  ",len(train_labels))
print("Test_Images  shape: ",test_images.shape)
print("Test_Labels  shape:  ",len(test_labels))

Train_Images shape:  (60000, 28, 28)
Train_Labels shape:   60000
Test_Images  shape:  (10000, 28, 28)
Test_Labels  shape:   10000


In [7]:
#import pandas as pd
##dir(pru)
#tipoDato = pd.DataFrame(data = pru, index = categorias)
#tipoDato

In [8]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [9]:
import cv2
prImg = cv2.imread("pruebaFoto.png")

In [10]:
prImg

array([[[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]],

       [[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]],

       [[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]],

       ...,

       [[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]],

       [[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]],

       [[ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71],
        ...,
        [ 76, 112,  71],
        [ 76, 112,  71],
        [ 76, 112,  71]]

In [11]:
print(type(train_images))
print(type(prImg))
print(prImg.shape)
print(prImg.size)
print(train_images[0].size)
print(train_images[0].shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(548, 448, 3)
736512
784
(28, 28)


In [12]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers import Flatten
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(64,activation="relu"),
    Dense(32,activation="relu"),
    Dense(128,activation="relu"),
    Dense(10,activation="softmax"),
])

In [13]:
model.compile(optimizer="adam",
             loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 64)                50240     
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 128)               4224      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 57,834
Trainable params: 57,834
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(train_images,train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 1ms/step - loss: 1.1536 - accuracy: 0.7353
Epoch 2/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5464 - accuracy: 0.8089
Epoch 3/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5008 - accuracy: 0.8235
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4642 - accuracy: 0.8360
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4366 - accuracy: 0.8472
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4202 - accuracy: 0.8515
Epoch 7/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4005 - accuracy: 0.8579
Epoch 8/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3926 - accuracy: 0.8610
Epoch 9/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3758 - accuracy: 0.8666
Epoch 10/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.366

In [15]:
test_loss, test_acc = model.evaluate(test_images,test_labels)
print("Test Accuracy: ",test_acc)
print("Test Loss: ",test_loss)

313/313 [==============================] - 1s 1ms/step - loss: 0.4272 - accuracy: 0.8515
Test Accuracy:  0.8514999747276306
Test Loss:  0.42718514800071716


In [16]:
prediction= model.predict(test_images)
print("tipo: ",type(test_images[0]))

tipo:  <class 'numpy.ndarray'>


In [17]:
# ahora vamos a ver cual tiene el valor más alto de seguridad
print(np.argmax(prediction[0]))
print(test_labels)

9
[9 2 1 ... 8 1 5]


# Vamos a definir algunas funciones utiles

In [18]:
def porcentajes(i,predictions_array,true_label,img):
    predictions_array,true_label,img = predictions_array[i],true_label[i],img[i]
    predicted_label = np.argmax(predictions_array)
    texto = categorias[predicted_label], " ",100*np.max(predictions_array), " ", categorias[true_label]
    lblPorcentaje = Label(raiz,text=texto,bg="#077AAE",fg="#FEFEFE").pack()

In [19]:
len(prediction)

10000

In [20]:
#import matplotlib.patches as patches
#import matplotlib.cbook as cbook
from PIL import Image
#from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
raiz = Tk()
raiz.geometry("450x350")
raiz.title("Clasificador")
frame= Frame(raiz, bg="blue")
entero_prueba = ttk.Entry(raiz,width=20)
entero_prueba.pack()
lblPorcentaje = Label(raiz,text="",bg="#077AAE",fg="#FEFEFE").pack()
i=0

# aquí vamos a ver que tan probable es que salga esta imagen
def testeo_si_testeo():
    i= int(entero_prueba.get())
    porcentajes(i,prediction,test_labels,test_images)

In [21]:
boton_prueba= Button(raiz, text="Ver", command=testeo_si_testeo)
boton_prueba.pack()
img2 = Image.fromarray(test_images[i])

#####################################################################################
# Inge creo que estos directorios los va tener que cambiar si quiere que le funcione
#####################################################################################

img2.save('C:\\Users\\HP15DA0023LA\\Untitled Folder\\my.png')
ix = PhotoImage(file="C:\\Users\\HP15DA0023LA\\Untitled Folder\\my.png")
lbl_img = Label(raiz, image = ix)
lbl_img.pack()

In [22]:
raiz.mainloop()